# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.PositiveIntegerField(null=True)),
                ('role', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('both', 'Both')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('selling_started_on', models.DateField()),
                ('selling_ends_on', models.DateField()),
                ('despatched_from', models.CharField(max_length=50)),
                ('sellerid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
