# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.IntegerField()),
                ('despatch_time', models.DateTimeField()),
                ('buyer', models.ManyToManyField(related_name='transaction_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Wares',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ManyToManyField(to='cart.Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ManyToManyField(related_name='transaction_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
