# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20160323_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_ends_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_started_on',
            field=models.DateField(null=True),
        ),
    ]
