# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20160323_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='product',
            new_name='product_name',
        ),
    ]
