# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_started_on',
            new_name='selling_starts_on',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_pictures/%Y/%m/%d'),
        ),
    ]
