# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20160329_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time']},
        ),
    ]
