# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import dragimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dragimage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer_id', models.CharField(db_column='customer_id', max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=30, null=True)),
                ('user_name', models.CharField(db_column='user_name', max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, db_column='email_id', max_length=50, null=True)),
                ('user_image1', models.ImageField(db_column='user_image1', upload_to=dragimage.models.get_upload_path)),
                ('user_image2', models.ImageField(db_column='user_image2', upload_to=dragimage.models.get_upload_path)),
                ('user_image3', models.ImageField(db_column='user_image3', upload_to=dragimage.models.get_upload_path)),
                ('user_image4', models.ImageField(db_column='user_image4', upload_to=dragimage.models.get_upload_path)),
                ('user_image5', models.ImageField(db_column='user_image5', upload_to=dragimage.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='FourthTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=dragimage.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=dragimage.models.get_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='../dragimage_pictures/%Y/%m/%d'),
        ),
    ]
