# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragimage', '0002_auto_20160914_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourthtry',
            name='id',
        ),
        migrations.AddField(
            model_name='fourthtry',
            name='picture_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fourthtry',
            name='picture',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
