# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragimage', '0004_auto_20160916_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourthtry',
            name='picture_id',
        ),
        migrations.AddField(
            model_name='fourthtry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
