# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragimage', '0005_auto_20160916_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthtry',
            name='picture_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fourthtry',
            name='picture_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
